version: "2"

services:
  api:
    build: ../src/ExamApp.Api
    links:
      - mongo
    ports:
      - '5000:5000'

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    